### ISSUE TITLE
no matter what ollama model used, same error appears (ollama itself and models works fine, either via cli or api just not plugin)

### ISSUE THREAD

**Issue by pracplayopen** [julian-shalaby/Onuro-feedback#12]
EXPECTED:

open a file, select the model, enter a query in chat window about the code, get a relevant response.

INSTEAD:

regardless of model, an timeout error is generated

PROCEDURE:

run chatwindow like:

1. open a file in jetbrains rider
2. in chatwindow, from llm dropdown, select ollama and then select a local model (eg phi3:latest)
3. then from files dropdown, select only the open file i want to chat about
4. then enter query in the chat prompt under 'type a message', eg "please describe what method XXXXX does in FILENAME.xyz"

regardless of model used, this appear appears... usually in a few seconds:

> Request timed out. Please make sure the model is running and functional.
To run the model, run "ollama run phi3:latest" in your terminal.
To ensure its functional, send the model a message once its running in your terminal.

in the background the model can be seen to be running successfully, and the same query can be sent successfully to the model w/out using the plugin.

SYSTEM + PLUGIN INFO:

JetBrains Rider 2024.1.4
Build #RD-241.18034.76, built on June 23, 2024
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Non-Bundled Plugins:
  com.github.julianshalaby.chatwindow (1.4.2)

$ ollama --version
ollama version is 0.1.47

**Comment by julian-shalaby** [comment]
Hey! Apologies for the lack of support here, but this 1 will have to stay unfixed. The reason being that a few months ago, I began to completely redo the project from scratch, and let the current implementation die out. Expect a v2 within the next 3-6 months. Also, Ollama support may not be there on day 1, but it is on the roadmap to be re-implemented.
