### ISSUE TITLE
Chat window is blank on  PyCharm 2024.1.5, Ubuntu 24.04 LTS, Xfce desktop

### ISSUE THREAD

**Issue by hfanous** [julian-shalaby/Onuro-feedback#13]
ChatWindow plugin which was working fine until recent updates, now shows blank plugin window.  reverting back to earlier version of PyCharm does not fix the problem.

IDE: PyCharm 2024.1.5,
OS:  Ubuntu 24.04 LTS
Desktop: Xfce 
ChatWindow 1.4.2

[idea.log](https://github.com/user-attachments/files/16741137/idea.log)

PyCharm IDE Log file is attached.

Please let me know if other information is required.

Thanks

Hani

**Comment by julian-shalaby** [comment]
I'll update this soon. Thank you for pointing it out

PS - The current ChatWindow project is dead. A few months ago I began completely redoing the project from scratch. Expect a HUGE update in 3-6 months
