### ISSUE TITLE
Not compatible with the version of your running IDE (PhpStorm 2024.1 Beta)

### ISSUE THREAD

**Issue by CrazyBoy49z** [julian-shalaby/Onuro-feedback#2]
Add support

**Comment by julian-shalaby** [comment]
@CrazyBoy49z update is under review rn! Caught this yesterday and pushed a fix for it

**Comment by julian-shalaby** [comment]
@CrazyBoy49z And just got sent the approval email. Version 1.2.3 should work. Let me know if you run into an issue

**Comment by CrazyBoy49z** [comment]
Thanks
