### ISSUE TITLE
Feature request. Select default model. Change visibility state of "voice to text" button.

### ISSUE THREAD

**Issue by 0fuz** [julian-shalaby/Onuro-feedback#3]
Hello, i would'be happy to see this updates:
- option to hide button "voice-to-text"
- option to not use "free" model by default. Its a change to start chatting with claude about project secrets instead of ollama local runned node.

**Comment by julian-shalaby** [comment]
@0fuz will keep this in mind, but I'm a bit skeptical to make either of these changes

for speech to text - I try not to add more toggles unless I really need to, as this can quickly overwhelm the UI. Unless this is a common request, this will likely stay as is. Just wondering, what is your reasoning behind wanting this removed?

for ollama - this is a bit unsafe imo. Most users do not have ollama, and for those that do, defaulting to ollama isn't always a great experience. I find models run through ollama will sometimes take a bit to respond if it's the first message in a while, sometimes the ollama app will require a restart if left open and unused for too long, and many users can't run any models nearly as powerful as claude 3 haiku. I understand it is common to have safety concerns around sending data to providers though. Would it work for you if I always reset the model selection to your last used model, making it much less likely to use a provider hosted model?

**Comment by 0fuz** [comment]
> "speech to text". Just wondering, what is your reasoning behind wanting this removed?

Im not planning to use this button so thought its possible to hide it under 'settings' to make chat ui one more button less. Its not hot problem, no problem)

> Would it work for you if I always reset the model selection to your last used model, making it much less likely to use a provider hosted model?

Yes, select last used model for new chat or reopened chat. Its would'be enough, thanks.

**Comment by julian-shalaby** [comment]
@0fuz Will add this (or something similar to set a default model) in the next update. Expect this within the next month. Next update will probably be pretty big, so taking a bit longer on this 1
