### ISSUE TITLE
Connect more models via PRs

### ISSUE THREAD

**Issue by 0fuz** [julian-shalaby/Onuro-feedback#5]
Hello again.

I love how simple selecting the model here. And i think connecting most of models to plugin can be standartised like ollama and chatgpt rest api have. So any other public/private/free/selfhosted models might be added via PRs which implements some standartised interface.

For example:
- command r https://docs.cohere.com/reference/about
- together ai https://docs.together.ai/docs/inference-rest
- phind https://github.com/fiery-transition/phindapidocs/blob/main/README.md

Not sure about how hard to make standad connector with context and chat but in category "IDE + Code assistant" there is free space for good plugin which is not incorporated to only one model and simple to use without a lot of params required to be done by user.

Im glad about user experience here (context, model selection). Hope plugin can come open-source to allow PRs.

**Comment by julian-shalaby** [comment]
* Command R will be in the next update. This is implemented in my current dev branch. Great model for sure
* Together AI actually might be good to add in. Will consider this and probably add this in too
* Phind I agree would likely be nice.. Only problem is they don't have an official API. Once they support an official API, will definitely consider adding them as well
* Not mentioned, but Groq API support will be added in the next update as well

The plugin will not be open sourced. With that being said, supporting an additional provider is only about a 10 min task for me. Will consider supporting user defined providers as well

**Comment by Shrulik** [comment]
Hey, I suggest also supporting AWS bedrock. It gives access to multiple models, and many people already pay for models that way and prefer not to subscribe additionally to the same model, like Claude. 

Another thing, might be a different issue. When connecting to the Google AI studio via the API key, I can only select Gemini Pro 1.0 model and there is no option to select the other models available via the key. 

<img width="167" alt="image" src="https://github.com/julian-shalaby/ChatWindow-feedback/assets/1359443/cd3abc45-edb9-4b47-90b2-870a7b56c15f">

**Comment by julian-shalaby** [comment]
Hey guys, sorry for not releasing an update in awhile. I had some ideas for some major changes, and started redoing ChatWindow a few months ago. It will be another 6-9 months before I release, but unfortunately I will be taking the approach of not supporting API keys or Ollama at all.

**Comment by julian-shalaby** [comment]
PS - Really hope you guys like the V2! Obviously will be some tradeoffs in the underlying architecture, but I expanded the scope a lot and put tons of effort into making the experience much better
