### ISSUE TITLE
Setting for Ollama Context Window Size

### ISSUE THREAD

**Issue by bkonia** [julian-shalaby/Onuro-feedback#6]
In the Ollama configuration, can you please provide an option to specify the context window size? I know we can set this in Ollama directly, but it would be much more convenient to be able to specify it in ChatWindow.

**Comment by julian-shalaby** [comment]
Hey! So in addition to my comment in [here](https://github.com/julian-shalaby/ChatWindow-feedback/issues/7), I unfortunately will be discontinuing Ollama support in the future. For the past few months I have been working on a V2 of ChatWindow. With many architectural changes, and the scope being expanded to cover much more than the current version, I came to the conclusion that the development overhead is just too risky to attempt taking on.

Would love to support Ollama, but the V2 architecture really makes this difficult. A seamless integration that addresses all data privacy concerns would require a ton of development overhead, or a bunch of hacky layers of redirection. I understand this is a big downside to many users, but hopefully the upsides outweigh this tradeoff
